name: Flask-Dash-App
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - bottleneck=1.3.8
  - pip:
      - ipykernel==6.29.3
      - ipython==8.22.2
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - pandas==2.2.2
      - dash==2.17.0
      - dash-bootstrap-components==1.6.0
      - Flask==3.0.3
      - Flask-SQLAlchemy==3.1.1
      - SQLAlchemy==2.0.29